[tool.poetry]
name = "cat-ai"
version = "0.0.5-alpha"
description = "Python client for running CAT tests in a Python codebase"
authors = [
  "Mike Gehard <mikegehard@artium.ai>",
  "Randy Lutcavich <randylutcavich@artium.ai>",
  "Erik Luetkehans <erikluetkehans@artium.ai>",
  "Paul Zabelin <paulzabelin@artium.ai>",
  "Tim Kersey <timkersey@artium.ai>",
]
readme = "README.md"
packages = [{ include = "cat_ai", from = "src" }]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.13"
pydantic = "^2.10.6"
pydrive2 = "^1.21.3"

[tool.poetry.group.test.dependencies]
pytest = "^8.3.4"
pytest-asyncio = "^0.21.0"
mypy = "^1.8.0"
black = "^24.2.0"
flake8 = "^7.0.0"

[tool.poetry.group.examples.dependencies]
openai = "^1.63.2"
python-dotenv = "^1.0.1"

[tool.poetry.group.dev.dependencies]
sphinx = "^8.1.3"
sphinx-rtd-theme = "^3.0.2"
sphinx-markdown-builder = "^0.6.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
asyncio_mode = "auto"
pythonpath = [".", "src"]
testpaths = ["tests"]

[tool.mypy]
python_version = "3.13"
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
warn_unreachable = true
strict_optional = true
namespace_packages = true
explicit_package_bases = true
mypy_path = ["src"]

[tool.black]
line-length = 120
target-version = ['py313']
include = '\.pyi?$'
