name: 'Commit Visualizations'
description: 'Commits generated visualization PNGs and optionally a DB file to the repo'

inputs:
  path:
    description: 'Path to the directory containing PNG files'
    required: true
  db_path:
    description: 'Path to the database file to commit (optional)'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Configure Git
      shell: bash
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Sync with remote main
      shell: bash
      run: |
        git fetch origin main
        git reset --hard origin/main

    - name: Commit visualization PNG files and optional DB
      shell: bash
      run: |
        echo "Checking for PNG files in ${{ inputs.path }}"
        find ${{ inputs.path }} -name "*.png" -type f

        # Stage PNG files (if any)
        git add -v ${{ inputs.path }}/*.png || true

        # If db_path is provided and file exists, stage it
        if [ -n "${{ inputs.db_path }}" ] && [ -f "${{ inputs.db_path }}" ]; then
          echo "Staging DB file at ${{ inputs.db_path }}"
          git add -v "${{ inputs.db_path }}" || true
        else
          echo "No DB file to commit or file not found."
        fi

        # Commit changes (if any)
        git commit -m "Update visualization PNGs${{ inputs.db_path && ' and DB file' || '' }}" || echo "No changes to commit"
        git push
