name: CAT

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ai_tests:
    name: AI Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python and Poetry
        uses: ./.github/actions/setup-python-poetry
        with:
          working-directory: .

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Run Example tests
        run: poetry run pytest examples/team_recommender
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Upload artifacts to Google Drive
        if: always()
        run: |
          zip -r test-output-${{ github.run_number }}.zip examples/team_recommender/tests/test_runs
          poetry run python src/cat_ai/publish_to_gdrive.py test-output-${{ github.run_number }}.zip
        env:
          GOOGLE_DRIVE_TEST_OUTPUT_FOLDER_ID: ${{ vars.GOOGLE_DRIVE_TEST_OUTPUT_FOLDER_ID }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
            name: test-output-${{ github.run_number }}
            path: examples/team_recommender/tests/test_runs

#      - name: Debugging with tmate
#        if: failure()
#        uses: lhotari/action-upterm@v1
#        with:
#          wait-timeout-minutes: 5